name: CI

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - src/**.js
      - package.json
      - test/commonjs/**
      - rollup.config.js
      - .github/workflows/commonjs.yml

jobs:
  commonjs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Node.JS version from package.json
        id: get-version
        run: echo ::set-output name=node::$(npx --q minimum-node-version)

      - uses: actions/setup-node@v3
        with:
          node-version: ${{steps.get-version.outputs.node}}

      - run: npm install

      - run: npm run prepublishOnly
